For creating an array

In [1]:
import numpy as np
list = [1, 2, 3, 4, 5]
array = np.array(list)
print(array)

[1 2 3 4 5]


In [2]:
print(type(array))

<class 'numpy.ndarray'>


In [3]:
import numpy
arr=numpy.array([1,2,3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
import numpy as np
arr=np.array([1,2,3])
print(arr)
print(type(arr))
print(np.__version__)

[1 2 3]
<class 'numpy.ndarray'>
1.24.3


using Data types

In [5]:
import numpy as np
my_array = np.array([1, 2, 3], dtype=np.float64)  # Creates an array with specified data type (float64 in this case)
print(my_array)

[1. 2. 3.]


In [6]:
import numpy as np
my_array = np.array([1, 2, 3], dtype=np.int32) 
print(my_array)

[1 2 3]


In [7]:
import numpy as np
my_array = np.array([1, 2, 3], dtype=np.complex128) 
print(my_array)

[1.+0.j 2.+0.j 3.+0.j]


In [8]:
import numpy as np
my_array = np.array([1,2,3], dtype=np.byte) 
print(my_array)

[1 2 3]


In [9]:
import numpy as np
zeros_array = np.zeros(5)  # Creates an array of 5 zeros
ones_array = np.ones((2, 3))  # Creates a 2x3 array of ones
print(zeros_array)
print(ones_array)

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
import numpy as np
zeros_array = np.zeros(5)+4  # Creates an array of 5 zeros
ones_array = np.ones((2, 3))+4  # Creates a 2x3 array of ones
print(zeros_array)
print(ones_array)

[4. 4. 4. 4. 4.]
[[5. 5. 5.]
 [5. 5. 5.]]


In [11]:
import numpy as np
zeros_array = np.zeros(5)*2  # Creates an array of 5 zeros
ones_array = np.ones((2, 3))*2  # Creates a 2x3 array of ones
print(zeros_array)
print(ones_array)

[0. 0. 0. 0. 0.]
[[2. 2. 2.]
 [2. 2. 2.]]


In [12]:
import numpy as np
zeros_array = np.zeros(5)-2  # Creates an array of 5 zeros
ones_array = np.ones((2, 3))-2  # Creates a 2x3 array of ones
print(zeros_array)
print(ones_array)

[-2. -2. -2. -2. -2.]
[[-1. -1. -1.]
 [-1. -1. -1.]]


In [13]:
import numpy as np   ###astype() method is used to specify the desired data type which is used to convert into integer format

zeros_array = (np.zeros(5) * 2).astype(int)
ones_array = (np.ones((2, 3)) * 2).astype(int)

print(zeros_array)
print(ones_array)


[0 0 0 0 0]
[[2 2 2]
 [2 2 2]]


In [14]:
import numpy as np
zeros_array = (np.zeros(5) * 2).astype(float)
ones_array = (np.ones((2, 3)) * 2).astype(float)

print(zeros_array)
print(ones_array)

[0. 0. 0. 0. 0.]
[[2. 2. 2.]
 [2. 2. 2.]]


In [15]:
import numpy as np
zeros_array = (np.zeros(5) * 2).astype(complex)
ones_array = (np.ones((2, 3)) * 2).astype(complex)

print(zeros_array)
print(ones_array)

[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
[[2.+0.j 2.+0.j 2.+0.j]
 [2.+0.j 2.+0.j 2.+0.j]]


In [16]:
import numpy as np

zeros_array_complex = (np.zeros(5) * 2).astype(str)
ones_array_complex = (np.ones((2, 3)) * 2).astype(str)

print(zeros_array_complex)
print(ones_array_complex)


['0.0' '0.0' '0.0' '0.0' '0.0']
[['2.0' '2.0' '2.0']
 ['2.0' '2.0' '2.0']]


In [17]:
import numpy as np

zeros_array_complex = (np.zeros(5) + 2).astype(bytearray)
ones_array_complex = (np.ones((2, 3)) + 2).astype(bytearray)

print(zeros_array_complex)
print(ones_array_complex)


[2.0 2.0 2.0 2.0 2.0]
[[3.0 3.0 3.0]
 [3.0 3.0 3.0]]


In [18]:
import numpy as np

zeros_array_complex = (np.zeros(5) * 2).astype(bytearray)
ones_array_complex = (np.ones((2, 3)) * 2).astype(bytearray)

print(zeros_array_complex)
print(ones_array_complex)


[0.0 0.0 0.0 0.0 0.0]
[[2.0 2.0 2.0]
 [2.0 2.0 2.0]]


In [19]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [20]:
import numpy as np
my_array = np.arange(0, 10, 2)  # Creates an array with values [0, 2, 4, 6, 8]
print(my_array)

[0 2 4 6 8]


In [21]:
import numpy as np
my_array = np.arange(0, 10)  # Creates an array with values [0, 2, 4, 6, 8]
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
import numpy as np
my_array = np.arange(0, 10, 4)  # Creates an array with values [0, 2, 4, 6, 8]
print(my_array)

[0 4 8]


In [23]:
import numpy as np
my_array = np.arange(1)  # Creates an array with values [0, 2, 4, 6, 8]
print(my_array)

[0]


In [24]:
import numpy as np
my_array = np.linspace(0, 1, 10)  # Creates an array with 5 values evenly spaced between 0 and 1
print(my_array)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [25]:
import numpy as np
random_array = np.random.rand(3, 3)  # Creates a 3x3 array of random values between 0 and 1
print(random_array)

[[0.88896221 0.91914251 0.74803819]
 [0.16796014 0.44981599 0.55500922]
 [0.30851949 0.69504498 0.33428144]]


In [26]:
import numpy as np
random_array = np.random.rand(5,2)  # Creates a 3x3 array of random values between 0 and 1
print(random_array)

[[0.96839137 0.53122005]
 [0.9636926  0.24958451]
 [0.67494492 0.6557194 ]
 [0.72677512 0.72506967]
 [0.40017536 0.07218807]]


In [27]:
import numpy as np
identity_matrix = np.identity(3)  # Creates a 3x3 identity matrix
diagonal_matrix = np.diag([1, 2, 3])  # Creates a diagonal matrix with specified values
print(identity_matrix)
print(diagonal_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [28]:
import numpy as np
identity_matrix = np.identity(4)  # Creates a 3x3 identity matrix
diagonal_matrix = np.diag([1, 1, 1])  # Creates a diagonal matrix with specified values
print(identity_matrix)
print(diagonal_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [29]:
import numpy as np
array1 = np.array([1, 2, 3])
                  
array2 = np.copy(array1)
print(array2)
print(array1)

[1 2 3]
[1 2 3]


In [30]:
import numpy as np
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array=np.concatenate((array1,array2))
print(array)

[1 2 3 4 5 6]


In [31]:
import numpy as np ###to add an element

array = np.array([1, 2, 3])
add=4
# Using np.append()
array = np.append(array, add)
print(array)

# Using concatenation
array = np.concatenate((array, np.array([add])))
print(array)


[1 2 3 4]
[1 2 3 4 4]


In [32]:
import numpy as np

array = np.array([1, 2, 3])
repeat = 3  ###repeat function will multiply with the specified value

extended_array = array * repeat
print(extended_array)

[3 6 9]


In [33]:
import numpy as np

array = np.array([1, 2, 3])
num_repeats = 3

extended_array = np.tile(array, num_repeats)   
##np.title function repeats the elements in an aray with a specified number of times
print(extended_array)


[1 2 3 1 2 3 1 2 3]


In [34]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
remove = 2 ###here index position of 2 will be removed

# Using indexing
array = np.delete(array, remove)
print(array)

# Using np.delete()
array = np.delete(array, [1,2])  # Remove multiple elements
print(array)


[1 2 4 5]
[1 5]


In [35]:
import numpy as np

scalar = np.array(4)  # Creating a 0D array (scalar)
print(scalar)


4


In [36]:
import numpy as np

array_1d = np.array([1, 2, 3])  # Creating a 1D array
print(array_1d)


[1 2 3]


In [37]:
import numpy as np

array_2d = np.array([[1, 2, 3], [4, 5, 6]])  # Creating a 2D array (matrix)
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [38]:
import numpy as np

array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])  # Creating a 3D array
print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [39]:
array_4d = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
print(array_4d)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


In [40]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])

shape = array.shape  # Returns the shape of the array
print(shape)


(2, 3)


In [41]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])

# Reshape a 1D array to a 2D array with shape (2, 3)
reshaped_array = array.reshape(2, 3)

In [42]:
print(reshaped_array)

[[1 2 3]
 [4 5 6]]


In [43]:
import numpy as np

# Creating a 1D array  of
array_1d = np.array([1, 2, 3, 4, 5])

# Creating a 2D array with shape of
array_2d = np.zeros((3, 4))

# Creating a 3D array with shape of
array_3d = np.ones((2, 3, 2))

array= np.empty([1])
print(array_1d)
print(array_2d)
print(array_3d)
print(array)

[1 2 3 4 5]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
[1.0609979e-313]


In [44]:
my_list = [10, 20, 30, 40, 50]
element = my_list[2]  # Access the element at index 2 (third element)
print(element) 


30


In [45]:
my_list = [10, 20, 30, 40, 50]
element = my_list[-1]  # Access the last element
print(element)  

50


In [46]:
my_list = [10, 20, 30, 40, 50]
subarray = my_list[1:4]  # Get elements at indices 1, 2, and 3
print(subarray)  

[20, 30, 40]


In [47]:
my_list = [10, 20, 30, 40, 50]
subarray = my_list[:]  # Copy the entire list
print(subarray)

[10, 20, 30, 40, 50]


In [48]:
my_list = [10, 20, 30, 40, 50, 60, 70]
subarray = my_list[1:6:2]  # Get every second element from index 1 to 5
print(subarray) 

[20, 40, 60]


In [49]:
my_list = [10, 20, 30, 40, 50]
subarray = my_list[-3:-1]  # Get elements at indices -3 and -2
print(subarray)  

[30, 40]
